spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
#  mvc:
server:
  servlet:
    context-path: /wyc
#    static-path-pattern: /res/**